### ISSUE TITLE
please update table design

### ISSUE THREAD

**Issue by smegcoffee** [smegcoffee/request_form#105]
My request
![image](https://github.com/user-attachments/assets/821512ec-9292-451f-9caa-92a37efd7940)

Approver Side
![image](https://github.com/user-attachments/assets/a885f9de-cbdb-47db-8b0d-9ec90a75e52d)

**Comment by noreenswan10** [comment]
This issue has been resolved. Thanks!

**Comment by smegcoffee** [comment]
thanks nor
