### ISSUE TITLE
fix margin mark status

### ISSUE THREAD

**Issue by smegcoffee** [smegcoffee/request_form#11]
![image](https://github.com/user-attachments/assets/039472cf-4f06-4a37-9bcf-46dc0a1653f5)

**Comment by noreenswan10** [comment]
This issue has been resolved. Thank you.

**Comment by smegcoffee** [comment]
![image](https://github.com/user-attachments/assets/3a3da96f-76ce-4e88-ae0c-a003db307a07)
sa my request nor

**Comment by smegcoffee** [comment]
thanks
