### ISSUE TITLE
Fix the login: if the user is an admin/user, they will be redirected to /dashboard; if they are an approver, they will be redirected to /dashboard/approver.

### ISSUE THREAD

**Issue by allanjustine** [smegcoffee/request_form#117]
Fix the login: if the user is an admin/user, they will be redirected to /dashboard; if they are an approver, they will be redirected to /dashboard/approver.

**Comment by allanjustine** [comment]
additonal added dashboard in approver no loading

**Comment by smegcoffee** [comment]
good job
