### ISSUE TITLE
fix loading state design

### ISSUE THREAD

**Issue by smegcoffee** [smegcoffee/request_form#13]
![image](https://github.com/user-attachments/assets/01734745-b9fc-4bdd-af51-22dc1aa667a6)
![image](https://github.com/user-attachments/assets/6e3e4b87-672e-48bf-9ddd-33c61021d58b)
![image](https://github.com/user-attachments/assets/bc2c2127-77b6-4c13-9d40-2ca2e117be79)
![image](https://github.com/user-attachments/assets/59b01327-a8df-4584-93eb-8e272671c076)
![image](https://github.com/user-attachments/assets/73c78e4e-5b16-4c4e-bfba-14a8594ee968)

**Comment by allanjustine** [comment]
![image](https://github.com/user-attachments/assets/12474d94-d093-4156-a270-d4f4330f44f0)


loading state color changed to light not dark

**Comment by smegcoffee** [comment]
thanks
