### ISSUE TITLE
Fix clear button in signature

### ISSUE THREAD

**Issue by jenecilpatac** [smegcoffee/request_form#25]
![Clipboard - October 11, 2024 9_59 AM](https://github.com/user-attachments/assets/d510e0b9-b077-45c6-81d7-a94b0859f631)

**Comment by allanjustine** [comment]
naunsa ang button?

**Comment by jenecilpatac** [comment]
di ma clear ang signature

**Comment by allanjustine** [comment]
All goods in a hoods

**Comment by smegcoffee** [comment]
good
