### ISSUE TITLE
Fix Signature of Requested By in Some of the Print Pages

### ISSUE THREAD

**Issue by noreenswan10** [smegcoffee/request_form#28]
![image](https://github.com/user-attachments/assets/8097e1df-0636-4062-9e4e-95a4314c011f)
![image](https://github.com/user-attachments/assets/21746380-4b96-4385-8392-3616de24d983)
![image](https://github.com/user-attachments/assets/07c4f608-fb67-413b-9f1a-ec0316add358)
![image](https://github.com/user-attachments/assets/f408ee98-23b7-4e4d-851d-8db907c20447)
![image](https://github.com/user-attachments/assets/69d78f52-6146-437c-a18b-faccc6e6b4bd)
![image](https://github.com/user-attachments/assets/b74f5fd4-3f3b-4a7f-8029-c3863507ac3b)
**Note: EXCEPT STOCK REQUISITION FORM**

**Comment by noreenswan10** [comment]
This issue has been addressed. Thank you!

**Comment by smegcoffee** [comment]
Well done!
