### ISSUE TITLE
Cannot delete disapproved request

### ISSUE THREAD

**Issue by macmac-prog** [smegcoffee/request_form#37]
![image](https://github.com/user-attachments/assets/e2ba49cc-60d1-4f7f-adeb-c754f32aae11)

**Comment by smegcoffee** [comment]
ma wala sya sa page but naa lang ghapon sa database 
bali ang status lang niya 
if status = deleted then dli mo show

**Comment by allanjustine** [comment]
All Goods in the hoods
in the middle of the hoods

**Comment by smegcoffee** [comment]
thanks
