### ISSUE TITLE
Fix Approver Request Branch not displaying

### ISSUE THREAD

**Issue by noreenswan10** [smegcoffee/request_form#38]
![image](https://github.com/user-attachments/assets/593d9b9e-5ff4-4bb0-ad51-ceb2ae44430a)

**Comment by jenecilpatac** [comment]
local na? naa ra lge sa live
![image](https://github.com/user-attachments/assets/f7c52728-83b8-4e06-85c2-34720c00c784)

**Comment by noreenswan10** [comment]
Ouh local. naa siguroy natandog ani sa mga pag updates. @jenecilpatac

**Comment by noreenswan10** [comment]
Ahh siguro tungod kay Head Office sya dili branch? @jenecilpatac

**Comment by smegcoffee** [comment]
ok naman siguro ni
