### ISSUE TITLE
please fix in printing and cash advance not required in liquidation

### ISSUE THREAD

**Issue by smegcoffee** [smegcoffee/request_form#42]
![image](https://github.com/user-attachments/assets/25de2908-eda2-4ea8-a0d3-314da5bb6951)

**Comment by noreenswan10** [comment]
@emi-Meg 
**CASH ADVANCE NOT REQUIRED IN LIQUIDATION FORM** Additional fixation here, in this issue.

**Comment by smegcoffee** [comment]
great work
