### ISSUE TITLE
Fix black loader to white in admin side particularly in user, branch, approver, AVP Staff, Area Manager and Branch Head

### ISSUE THREAD

**Issue by jenecilpatac** [smegcoffee/request_form#43]
Fix black loader to white in admin side particularly in user, branch, approver, AVP Staff, Area Manager and Branch Head

![image](https://github.com/user-attachments/assets/b7e10118-9f19-40d4-9f40-5d803cf948ed)

**Comment by smegcoffee** [comment]
all goods na ni jen
