### ISSUE TITLE
No records found in My Request Page

### ISSUE THREAD

**Issue by noreenswan10** [smegcoffee/request_form#44]
I created a request successfully, but no records found in My Request page.
![image](https://github.com/user-attachments/assets/6bc90680-8d4f-4bb9-bd51-f3d61c1b5fc9)

**Comment by jenecilpatac** [comment]
tungod na kay wa na migrate ang complete_code nga column sa request_forms table

**Comment by noreenswan10** [comment]
how unsaon @jenecilpatac

**Comment by noreenswan10** [comment]
Done thank you!
