### ISSUE TITLE
change approved request to completed if the request already done

### ISSUE THREAD

**Issue by smegcoffee** [smegcoffee/request_form#6]

**Comment by smegcoffee** [comment]
fix profile loading

**Comment by allanjustine** [comment]
![{ACC6B3A6-D64D-4958-885A-80958046D611}](https://github.com/user-attachments/assets/868955e2-e9ff-4ecb-9d93-85784d705c12)

Change if all noted by and approved by is approved to a request it will become Completed

**Comment by smegcoffee** [comment]
nicely work
