### ISSUE TITLE
fix avp finance staff users

### ISSUE THREAD

**Issue by smegcoffee** [smegcoffee/request_form#66]
- add avp finance staff position
- fix ongoing ? icon , add to pusher

remove avp finance staff to the approvers
![image](https://github.com/user-attachments/assets/0c85c254-d45e-44d0-917a-3d17e957c085)
![image](https://github.com/user-attachments/assets/a616ab08-d41e-4a40-96cc-a95c62da89f7)

no approvers on avp finance staff users
![image](https://github.com/user-attachments/assets/2b565f0c-7fa2-4435-898a-560752540f6b)

**Comment by allanjustine** [comment]
Done !

**Comment by smegcoffee** [comment]
very good
