### ISSUE TITLE
add security level on creating an account

### ISSUE THREAD

**Issue by smegcoffee** [smegcoffee/request_form#67]
all newly registered users need to be accepted by the admin

**Comment by allanjustine** [comment]
Done security level on creating an account added!

**Comment by smegcoffee** [comment]
![image](https://github.com/user-attachments/assets/c6f726f2-bce1-431e-a109-7d658ca41c8e)

**Comment by allanjustine** [comment]
Goods in the hoods

**Comment by smegcoffee** [comment]
good job!
