### ISSUE TITLE
create new page, add link to the sidebar "Position"

### ISSUE THREAD

**Issue by smegcoffee** [smegcoffee/request_form#68]
![image](https://github.com/user-attachments/assets/955c16bc-2da8-4363-9437-a337dccf3ba5)

Show all positions and display the user assigned to each position
Add actions for editing and deleting with confirmation using SweetAlert (only position)

- gather all positions for later setup

**Comment by smegcoffee** [comment]
also,
branch code must display here:
![image](https://github.com/user-attachments/assets/e0dccd38-052d-4fec-9dc6-ed984b2acb81)

**Comment by noreenswan10** [comment]
Added additional component for 'Position' Page in Admin Panel. Please note that the sample data are in the same file since it was just temporary and will delete after making database table for position.
P.S. There is no handleSubmit function yet and SWAL. @macmac-prog  @emi-Meg

**Comment by allanjustine** [comment]
Done!

**Comment by smegcoffee** [comment]
thanks! good job
