### ISSUE TITLE
Update the request to be approved. If the request has been deleted, an alert will notify that the request is already deleted.

### ISSUE THREAD

**Issue by allanjustine** [smegcoffee/request_form#92]
Additionally, in the dashboard, add a loading indicator for Total, Pending, Approved, and Unsuccessful requests before fetching the total numbers. Also, when deleting a request, the table shows a loading indicator, which is annoying, so please remove it.

**Comment by allanjustine** [comment]
Done !

**Comment by smegcoffee** [comment]
good
