### ISSUE TITLE
Fix liquidation cant save if 0 or empty cash advance, change the icon from folder to file document, fix total amount instead of NaN change to 0

### ISSUE THREAD

**Issue by allanjustine** [smegcoffee/request_form#94]
Fix liquidation cant save if 0 or empty cash advance, change the icon from folder to file document, fix total amount instead of NaN change to 0

**Comment by allanjustine** [comment]
Done!

**Comment by allanjustine** [comment]
Adding additional changes in profile.tsx

**Comment by smegcoffee** [comment]
thanks
